---
title: "enzyme_activity2_analysis"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, echo = FALSE,results = FALSE, message = FALSE}
library(here)
library(tidyverse)
library(ggpubr)
library(conflicted)
library(ggprism)
```

```{r read in and format data, results = FALSE, message = FALSE, warning=FALSE}
experiment <- "enzyme_activity_assay"
data <- readr::read_csv(file = here(experiment, "example 2", "data", "enzyme_activity2_OD450.csv"), locale=locale(encoding="latin1"))

samplenames <- c("condition1_rep1", "condition3_rep1",
                 "condition1_rep2", "condition3_rep2",
                 "condition1_rep3", "condition3_rep3",
                 "condition1_rep4", "condition3_rep4",
                 "condition2_rep1", "posCtrl_rep1",
                 "condition2_rep2", "posCtrl_rep2",
                 "condition2_rep3", "blank_rep1",
                 "condition2_rep4", "blank_rep2")
                 

stopifnot(length(colnames(data)) == length(samplenames))

colnames(data) <- samplenames

blanks <- data[,grepl(pattern = "blank", colnames(data))]

data <- data %>% mutate(blank_NA = (blank_rep1 + blank_rep2) / 2)

tmp <- data %>%
  purrr::keep(is.numeric) - data$blank_NA

tmp <- tmp %>% rownames_to_column(var = "Time")

data_norm <- tmp[,!grepl(pattern = "blank", colnames(tmp))]

data_norm <- pivot_longer(data_norm, 
                          cols = condition1_rep1:condition2_rep4, 
                          names_to = "sample")
  
data_norm <- data_norm %>% 
  separate(col = sample,
           into = c("sample", "rep"))
```

```{r plot OD v time, message = FALSE, results = FALSE, fig.dim = c(4,4), echo = FALSE, warning=FALSE}
times <- as.character(c(1:121))
data_norm$Time <- factor(data_norm$Time, levels = times)
data_norm$rep <- factor(data_norm$rep, levels = c("rep1", "rep2", "rep3", "rep4", "NA"))
data_norm$sample <- factor(data_norm$sample, levels = c("condition1", "condition2", "condition3", "posCtrl", "blank"))

colnames(data_norm)[4] <- "OD450_norm"



  tmp <- as.character(unique(data_norm$sample))
  plots <- list()
#  prettycolors <- c("grey10", "grey20", "grey30", "grey40", "grey50", "grey60", "grey70", "grey80", "grey90", "grey100")
  
  
# QC: making sure none of the rep wells came out significantly different than the others before I average them together
for (i in 1:length(tmp)) {
  plots[[i]] <- (data_norm[grep(pattern = tmp[i], data_norm$sample),]) %>%
  ggplot() +
  geom_line(aes(x=Time, y=OD450_norm, color = rep, group = interaction(sample, rep)), linewidth = 1.5) +
  theme_prism() +
#  scale_color_manual(values = c("grey10", "grey90", "grey30", "grey65")) + # had to put it in color because the grey is so hard to see
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle(as.character(tmp[i]))
}

cowplot <- cowplot::plot_grid(plotlist = plots)

ggplot(data_norm) +
  geom_line(aes(x = Time, y = OD450_norm, color = sample, group = interaction(sample, rep)))

ggsave(plot = cowplot, filename = here(experiment, "example 2", "results", "enzyme_activity2_plot.png"), device = "png", height = 10, width = 10, bg = "white")

data_norm <- data_norm[!grepl(pattern = "blank", data_norm$sample),]

```


```{r calculate activity, warning=FALSE}
data_activity <- data_norm[grepl(pattern = 120, data_norm$Time),]

data_activity$OD30 <- data_norm[grepl(pattern = 30, data_norm$Time),]$OD450_norm
data_activity$OD200 <- data_norm[grepl(pattern = 120, data_norm$Time),]$OD450_norm
data_activity$activity <- (data_activity$OD200 - data_activity$OD30) / 90

data_activity <- data_activity %>%
  dplyr::select(!Time) %>%
  dplyr::select(!OD450_norm)

data_activity$rep <- factor(data_activity$rep, levels = c("rep1", "rep2", "rep3", "rep4", "NA"))
data_activity$sample <- factor(data_activity$sample, levels = c("condition1", "condition2", "condition3", "posCtrl"))

write_csv(data_activity, file = here(experiment, "example 2", "results", "enzyme_activity2_processeddata.csv"))
```

```{r plot activity, warning=FALSE}
activityplot <- data_activity %>%
  dplyr::filter(sample != "posCtrl") %>%
  ggplot(aes(x = sample, y = activity, fill = sample)) +
  geom_boxplot(outliers = FALSE) +
  geom_jitter(color = "black", size = 2, width = 0.1) +
  theme_prism() +
  scale_fill_manual(values = c("grey75", "grey50", "grey25")) +
  theme(legend.position = "none") +
  ggtitle("enzyme_activity2 activity assay")

ggsave(plot = activityplot, filename = here(experiment, "example 2", "results", "enzyme_activity2_activityPlot_yaxismod.png"), device = "png", width = 6, height = 5)

```