---
title: "enzyme_activity_assay_example"
author: "Libby Murphy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, echo = FALSE,results = FALSE, message = FALSE}
library(here)
library(tidyverse)
library(conflicted)
library(readr)
library(purrr)
library(ggpubr)
library(viridis)
library(RColorBrewer)
library(ggplot2)
library(ggprism)
```

```{r read in and format data, results = FALSE, message = FALSE, warning=FALSE}
experiment <- "enzyme_activity_assay"

data <- readr::read_csv(file = here(experiment, "example 1", "data", "enzyme_activity_data.csv"), locale=locale(encoding="latin1"))

times <- as.character(c(1:121))
data$Time <- times

samplenames <- c("RnoMitoControl_DF1", "Human03_DF2", "Human06_DF1", "Human08_DF4", 
                 "Human01_DF1", "Human03_DF4", "Human06_DF2", "Human09_DF1", 
                 "Human01_DF2", "Human04_DF1", "Human06_DF4", "Human09_DF2",
                 "Human01_DF4", "Human04_DF2", "Human07_DF1", "Human09_DF4",
                 "Human02_DF1", "Human04_DF4", "Human07_DF2", "Human10_DF1",
                 "Human02_DF2", "Human05_DF1", "Human07_DF4", "Human10_DF2",
                 "Human02_DF4", "Human05_DF2", "Human08_DF1", "Human10_DF4",
                 "Human03_DF1", "Human05_DF4", "Human08_DF2")
                 

stopifnot(length(colnames(data)) == length(samplenames) + 1)

colnames(data)[c(2:length(colnames(data)))] <- samplenames

data_norm <- pivot_longer(data, 
                          cols = RnoMitoControl_DF1:Human08_DF2, 
                          names_to = "sample")
data_norm <- data_norm %>% 
  separate(col = sample,
           into = c("sample", "DF"))

type <- tibble(sample = unique(data_norm$sample)[2:11],
                      type = c("conditionA", "conditionB", "conditionA", "conditionB", "conditionB", "conditionB", "conditionB", "conditionA", "conditionA", "conditionB"))

data_norm <- left_join(data_norm, type, by = "sample")
```

```{r plot OD v time, message = FALSE, results = FALSE, fig.dim = c(4,4), echo = FALSE, warning=FALSE}
data_norm$Time <- factor(data_norm$Time, levels = times)
data_norm$DF <- factor(data_norm$DF, levels = c("DF1", "DF2", "DF4"))
data_norm$sample <- factor(data_norm$sample, levels = c("Human01", "Human04", "Human05", "Human06", "Human07", "Human09", "Human02", "Human03", "Human08", "Human10", "RnoMitoControl"))

colnames(data_norm)[4] <- "OD450_norm"

  tmp <- as.character(unique(data_norm$sample))
  tmp <- tmp[c(5,9,2,7,11,3,8,4,6,10,1)]
  plots <- list()
  prettycolors <- c("Blues", "Blues", "Blues", "Blues", "Blues", "Blues", "OrRd", "OrRd", "OrRd", "OrRd", "PRGn")
  
for (i in 1:length(tmp)) {
  plots[[i]] <- (data_norm[grep(pattern = tmp[i], data_norm$sample),]) %>%
  ggplot() +
  geom_line(aes(x=Time, y=OD450_norm, color = DF, group = interaction(sample, DF),linetype = sample), linewidth = 1.25) +
  ylim(0,0.195) +
  theme_classic() +
  scale_color_brewer(palette = prettycolors[i], direction = -1) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  ggtitle(as.character(tmp[i]))
}

cowplot <- cowplot::plot_grid(plotlist = plots, nrow = 2)

plots

ggsave(plot = cowplot, filename = here(experiment, "example 1", "results", "enzyme_activity_QCplots.png"), device = "png", height = 10, width = 20, bg = "white")

```

```{r calculate activity, warning=FALSE}
data_activity <- data_norm[grepl(pattern = 100, data_norm$Time),c(2,3,5)]

data_activity$OD30 <- data_norm[grepl(pattern = 30, data_norm$Time),]$OD450_norm
data_activity$OD120 <- data_norm[grepl(pattern = 120, data_norm$Time),]$OD450_norm
data_activity$activity <- (data_activity$OD120 - data_activity$OD30) / 90

data_activity$DF <- factor(data_activity$DF, levels = c("DF1", "DF2", "DF4"))
data_activity$type <- factor(data_activity$type, levels = c("conditionB", "conditionA"))

write_csv(data_activity, file = here(experiment, "example 1", "results", "enzyme_data_activity.csv"))
```

```{r plot activity, warning=FALSE}
pActivitycurves <- data_activity[!is.na(data_activity$type),] %>% 
  ggplot(aes(x = DF, y = activity, color = sample, group = sample)) +
  geom_line(aes(group = sample, linetype = type), linewidth = 1.5) +
  theme_classic() +
  ggtitle("enzyme activity curves")

pActivitycurves

ggsave(plot = pActivitycurves, filename = here(experiment, "example 1", "results", "enzyme_activityCurves.png"), device = "png")

```

```{r prism plotting}
dataset <- data_activity[!is.na(data_activity$type),] %>% dplyr::filter(DF == "DF1")

pBoxplots_prism <- dataset %>%
  ggplot(aes(x = type, y = activity), color = "black") +
  geom_boxplot(aes(fill = type)) +
  geom_jitter(size = 3.2, width = 0.08) +
  theme_prism() +
  ggtitle("example 1 enzyme activity") +
  ylab("normalized enzyme activity (AU)") +
  scale_fill_manual(values = c("gray30", "gray75")) +
  theme(legend.position = "none")

alt_p_val <- rstatix::t_test(dataset, activity ~ type, ref.group = "conditionB") %>%
  rstatix::add_xy_position()

pBoxplots_prism_pval <- pBoxplots_prism +
  add_pvalue(alt_p_val, y.position = 0.00125)

ggsave(plot = pBoxplots_prism, filename = here(experiment, "example 1", "results", "enzyme_activityBoxplots_ggprism.png"), height = 8, width = 8, device = "png")

ggsave(plot = pBoxplots_prism_pval, filename = here(experiment, "example 1", "results", "enzyme_activityBoxplots_ggprism_pval.png"), height = 8, width = 8, device = "png")

```

```{r stats}
sd(data_activity[!is.na(data_activity$type),] %>% dplyr::filter(type == "conditionA") %>% dplyr::select(activity) %>% as.matrix() * 90)
sd(data_activity[!is.na(data_activity$type),] %>% dplyr::filter(type == "conditionB") %>% dplyr::select(activity) %>% as.matrix() * 90)
```